start python main.py
start python main.py
start python main.py
start python main.py
start python main.py
start python main.py
start python main.py
start python main.py
start python main.py
start python main.py